#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Make launcher executable
    if [ -f /usr/bin/sqrt-gem ]; then
        chmod 755 /usr/bin/sqrt-gem
    fi

    # Update desktop database
    if which update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications || true
    fi

    # Update GTK icon cache
    if which gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi
fi

exit 0
